### ISSUE TITLE
Error Code 500 - Additional Documentation Unable To Be Generated

### ISSUE THREAD

**Issue by JohnLF1995** [cairis-platform/cairis#545] opened 2020-06-05 09:25 UTC
### Expected behavior
When documentation is requested to be generated, error code 500 appears.

### Actual behavior
When documentation is requested to be generated, error code 500 appears.

### Steps to reproduce the behavior
When documentation is requested to be generated or updated, error code 500 appears (works fine on Shamal's computer but not mine).

### Version of CAIRIS
05/06/2020 at 09:15

### Details of browser or, if applicable, details of the OS used to host CAIRIS

Chrome, Windows 10. Server: http://cairis.bournemouth.ac.uk:8000/

**Comment by failys** [comment] 2020-06-05 09:37
I can’t reproduce this on cairis.bournemouth.ac.uk on my account with the model you used. Can you please try producing documentation for a simple model to see if you can reproduce . If you can’t, try creating a new account and seeing if you can reproduce.

**Comment by JohnLF1995** [comment] 2020-06-05 09:56
So I tried a new account with a blank model, it worked. As soon as I imported the XML file I need to use, the same error code 500 occurred. So it must be something to do with the XML file, not CAIRIS. Any idea what the problem might be? I have sent the XML file to you directly.

**Comment by failys** [comment] 2020-06-05 10:06
Are there any reserved characters in the model. Running xmllint or some alternative tool to check for dodgy characters in the model should help.

**Comment by JohnLF1995** [comment] 2020-06-05 10:30
Not that i can see, removed all hyphens (-) and no difference. I have submitted now.

**Comment by failys** [comment] 2020-06-17 12:27
I can't reproduce this, so I'm closing for now.  Please re-open though if you can produce on a simple example.

**Closed by failys** 2020-06-17 12:27 UTC
