### ISSUE TITLE
No registeration link / No login details

### ISSUE THREAD

**Issue by mehrdadasadiut** [cairis-platform/cairis#662] opened 2023-01-30 13:37 UTC
### Expected behaviour
Login credentials / registeration link
Actually the guidelines for this type of installation did not mention even how to add users.
### Actual behaviour

No such credentials available / no link available
### Steps to reproduce the behaviour
Install cairis using " Installation and configuration of server with account registration via GitHub (automated) "

### Version of CAIRIS
latest

### Details of browser or, if applicable, details of the OS used to host CAIRIS

FireFox / UBUNTU 20.4

![Registeration](https://user-images.githubusercontent.com/111504275/215492393-67a1362e-5046-4ca5-a37a-8aff704705be.PNG)

**Comment by mehrdadasadiut** [comment] 2023-01-30 13:46
![Registeration](https://user-images.githubusercontent.com/111504275/215494380-08c74504-ad68-4eb9-a937-28f9399ea6f9.PNG)

However, there is a link for registration on remote clients. But it does not work.

**Comment by mehrdadasadiut** [comment] 2023-01-30 13:53
Server side logs.
![servererrorLog](https://user-images.githubusercontent.com/111504275/215495993-f4cd7f12-721d-4a09-ac10-34678540e72e.PNG)

**Comment by mehrdadasadiut** [comment] 2023-01-30 14:09
in Chrome the registeration / forget password icon is shown but it does not work as I mentioned in previous image.
I followed this:  
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/serverInstall.sh | bash -s my-secret-pw mymailserver.com 465 admin@mymailserver.com mypassword

with appropriate values of myself ofc.

**Comment by failys** [comment] 2023-01-30 14:20
I need to do a bit of digging around to get to the bottom of this issue.  The issue is almost certainly not with the CAIRIS code, but with the open-source dependencies it uses (likely Flask Security).  In the meantime, have you tried adding account manually on the server?  That should give you a workaround for now at least.

**Comment by failys** [comment] 2023-01-30 14:22
If the login button had a bug then you wouldn't be able to login into the live demo at https://demo.cairis.org.

**Comment by mehrdadasadiut** [comment] 2023-01-30 14:24
How I can add a user manually to see if CAIRIS logs me in on a remote client or not?

**Comment by mehrdadasadiut** [comment] 2023-01-30 14:41
I will use the manual registeration for now as you already provided the guideline.
Yes our priority is also the registration and a working cairis. We are a bit lack in dev staffs and currently had hard time to fix the issue and bring it up at least to first home page. 
Thanks for your help and consideration

**Comment by mehrdadasadiut** [comment] 2023-01-30 14:42
btw, the manual registration is working.

**Comment by failys** [comment] 2023-02-01 16:04
If you want to try doing a call install of a server with self-registration, this should now be working.  It took a bit longer than I hoped to fix this as I had to unpack the AuthN workflow to account for changes to the way SQLAlchemy works.  Things look good with the test cases, my own installation of a server with self-registration, and with the live demo, so - hopefully - things should be good for you too.

**Comment by failys** [comment] 2023-02-01 16:05
Closing for now, but we can re-open if this isn't resolved, or open a new issue if we find other problems off the back of this.

**Closed by failys** 2023-02-01 16:05 UTC
Labels: bug
