### ISSUE TITLE
The local server doesn't work. I have used vagrant/VM Box for installation.

### ISSUE THREAD

**Issue by mehrdadasadiut** [cairis-platform/cairis#644] opened 2022-08-18 11:58 UTC
Hello
I have used VM BOX 6.0 and Vagrant to install the CAIRIS.
Everything goes well and I have CAIRIS running on the VM.
The problem is when I try to use the localhost it does not work.
I am using windows 10 and VM Box. Do I need to do something before accessing to local host?

**Comment by failys** [comment] 2022-08-18 12:20
Is there anything unusual in the CAIRIS log file?  Also, can you try running up a browser within the VM and seeing what happens if you go to http://localhost:7071 from there?

**Comment by mehrdadasadiut** [comment] 2022-08-18 12:23
I did not check the log file.
The VM is in a running state but I cannot get into the VM itself.

**Comment by failys** [comment] 2022-08-18 12:25
The username / password is vagrant / vagrant.

**Comment by mehrdadasadiut** [comment] 2022-08-18 12:36
Sorry but I have logged in to the Vagrant using the credentials you just provided but I dont see any GUI that I can work with. Can I send you a screenshot?

**Comment by failys** [comment] 2022-08-18 12:37
Yes, by all means.

**Comment by mehrdadasadiut** [comment] 2022-08-18 12:38
![Vagrant VMBOX](https://user-images.githubusercontent.com/111504275/185396563-79864466-746f-44ff-ba76-ce4e78230a70.PNG)

**Comment by failys** [comment] 2022-08-18 12:46
Can you please try running `journalctl -u cairis | tail` and send me the output

**Comment by mehrdadasadiut** [comment] 2022-08-18 12:48
![cairis2](https://user-images.githubusercontent.com/111504275/185398508-65a6b1ef-755a-49c2-816a-bb0fb7b25f62.PNG)

Here the output is.

**Comment by failys** [comment] 2022-08-18 12:49
Also, can you try running `curl http://localhost:7071` to access the login page via the shell.

**Comment by failys** [comment] 2022-08-18 12:50
> ![cairis2](https://user-images.githubusercontent.com/111504275/185398508-65a6b1ef-755a-49c2-816a-bb0fb7b25f62.PNG)
> 
> Here the output is.

I don't see anything out of the ordinary here.

**Comment by mehrdadasadiut** [comment] 2022-08-18 12:52
Here is trying to enter by shell. I see nothing yet.
![cairi3](https://user-images.githubusercontent.com/111504275/185399164-6401e301-ea3d-4cf2-9f32-bf548bf2cb82.PNG)

**Comment by failys** [comment] 2022-08-18 12:55
That looks normal too.  The issue then doesn't seem to be with CAIRIS, but with accessing the VirtualBox .  I don't recall whether the flavour of Ubuntu this runs on has the firewall running by default, but you could try turning that off by running `ufw disable` and seeing if that helps.

I haven't installed CAIRIS via Vagrant for some time, so I'll try seeing if I can reproduce this problem.

**Comment by mehrdadasadiut** [comment] 2022-08-18 12:59
accessing the ufw command requires privilage and it doesnt work with : vagrant , vagrant
maybe you can try to somehow help me to check the problem by anyDesk or something ?

**Comment by mehrdadasadiut** [comment] 2022-08-18 12:59
or tell me what is the more easier / stable installation method for me?

**Comment by failys** [comment] 2022-08-18 13:03
Sorry, you need to prefix that command with sudo, i.e. `sudo ufw disable`.

In any event, it sounds like the issue here isn't with CAIRIS but networking through the VM itself.  If you're uncomfortable with Linux and want your own local installation of CAIRIS then installing via Docker might be your best bet.

**Comment by mehrdadasadiut** [comment] 2022-08-19 07:13
Sorry but I still have problems with the localhost, I Installed Docker and went through the procedure.

**Comment by failys** [comment] 2022-08-19 07:43
I think your Vagrant/VirtualBox problem might be related to #645.  I'm taking a look now, to see if this is the case.

**Comment by mehrdadasadiut** [comment] 2022-08-19 07:52
I tried to access http://VM_IP_ADDRESS:7071 on browser but it is unreachable. However, I tried to ping my VM IP it works ok.

**Comment by mehrdadasadiut** [comment] 2022-08-19 07:54
And I am sure installation of VM and Vagrant was much easier and less error than docker.  Docker had more commands to run and still both not working. 
So I would be happy if you could help me for the issue of Vagrant/VM.

**Comment by mehrdadasadiut** [comment] 2022-08-19 07:57
Omg look here. I used localhost without port number and Caris page is come up. How should I know that it is accesible from Docker or Vagrant / VM? 
However, I still cannot access the panel with user test and password test
![localhost without port num](https://user-images.githubusercontent.com/111504275/185572117-0915ea0e-553e-4ce6-a4e4-7cc4b57ff587.PNG)

**Comment by failys** [comment] 2022-08-19 07:57
The fix for #645 seems to work, but you'll need to go through the installation process again, i.e. run `vagrant destroy`, and run `vagrant up` again.  The problem was the CAIRIS dev server (that the VM uses) wasn't allowing external traffic to connect in.  I've fixed the quickInstall script the vagrant uses now, so all should be good.

**Comment by failys** [comment] 2022-08-19 07:59
> Omg look here. I used localhost without port number and Caris page is come up. How should I know that it is accesible from Docker or Vagrant / VM?
> However, I still cannot access the panel with user test and password test
> ![localhost without port num](https://user-images.githubusercontent.com/111504275/185572117-0915ea0e-553e-4ce6-a4e4-7cc4b57ff587.PNG)

It looks like you're using Docker.  Try logging in with test@test.com (password: test).  If the documentation is telling you to login as 'test' then please point me to where it says that and I'll fix it.

**Comment by failys** [comment] 2022-08-19 08:00
In any event, I _think_  your problems (with Vagrant/VirtualBox) should be resolved now, so I'll close this issue.  Please feel free to re-open if you're still getting problems though.

**Comment by mehrdadasadiut** [comment] 2022-08-19 08:00
Nothing happens. I cannot login. 
I am more interested to use Vagrant.

**Closed by failys** 2022-08-19 08:00 UTC
Labels: question
