### ISSUE TITLE
Impossible to add Naming conventions

### ISSUE THREAD

**Issue by rmainin** [cairis-platform/cairis#450] opened 2019-09-20 11:28 UTC
### Expected behaviour
When trying to add a naming convention, it should be shown in the list

### Actual behaviour
The list remains empty

### Steps to reproduce the behaviour
Open the system / properties  menu
go in the naming convention tab
click the +
fill the form in and click ok
the list remains empty

### Version of CAIRIS
2.1.4

**Comment by failys** [comment] 2019-09-20 11:36
Thanks for flagging this.  

I've just tried reproducing this with one of the sample models on demo.cairis.org but can't.  I just added the 'some convention' naming convention to the ACME Water model.  Can you please login (username/password is test/test) and see if you can reproduce this there. 

If you can't reproduce on the live demo, can you please try updating to the latest version (2.2.1 although the live demo is currently 2.2.0 until tomorrow morning).  This should fix this problem and any other issues you might not have found yet :-)

Given recent changes, 2.1.4 is a fairly old version and more recent updates fixed lots of instability/inconsistent behaviour you might have been experiencing.

**Comment by rmainin** [comment] 2019-09-20 11:59
Hello,

Thank you for this quick response.

It is weird, because I try to add a naming convention on the default database on the demo.cairis.org and it doesn’t work either.

Maybe this only happens when the table is empty? Or only with the default database.

Frederic

**Comment by rmainin** [comment] 2019-09-20 12:07
By the way, I would like to introduce myself a bit more but not on this platform.
if you mail me at frederic.hallot@rma.ac.be , I would be happy to tell you why and how we consider using CAIRIS

**Comment by failys** [comment] 2019-09-20 12:10
Ah ok - I can reproduce this problem now.  Let me take a look.....

**Comment by failys** [comment] 2019-09-20 14:22
Found the problem.  If you pull the latest sources, this should be fixed.

**Closed** 2019-09-20 14:22 UTC
