### ISSUE TITLE
Package not importing 

### ISSUE THREAD

**Issue by cryle2323** [cairis-platform/cairis#631] opened 2021-08-02 13:17 UTC
### Expected behaviour

I exported my work as a .cairis file yesterday. I am now trying to import it into cairis but when I press the import button I get a red X at the bottom of the page.

### Actual behaviour

Red X at the bottom of the page when importing cairis work

### Steps to reproduce the behaviour

Import a cairis package.

**Comment by cryle2323** [comment] 2021-08-02 13:18
What do I do to successfully import my Cairis work?

**Comment by failys** [comment] 2021-08-02 13:20
Have you followed the instructions here: https://cairis.readthedocs.io/en/latest/io.html#importing-models

**Comment by failys** [comment] 2021-08-02 13:21
if it doesn't work then let me know.

**Comment by cryle2323** [comment] 2021-08-02 13:23
Yes I have followed this to the exact step. 

I saved my work as a .cairis and am attempting to import the model using the .cairis model.

**Comment by failys** [comment] 2021-08-02 13:26
Please email the model to shamal.faily@gmail.com, so I can take a look.

**Comment by failys** [comment] 2021-08-05 21:18
Closing as this seems to be something that can't be reproduced.

**Closed by failys** 2021-08-05 21:18 UTC
